// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqBKTvs9ebqaw7YmcO40QXe_Nd5NutH58',
    appId: '1:851082001759:web:763d55b5f09e26c8344aea',
    messagingSenderId: '851082001759',
    projectId: 'broetchen-29bf0',
    authDomain: 'broetchen-29bf0.firebaseapp.com',
    storageBucket: 'broetchen-29bf0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCllHbrtSTVcsc7kyZ0RjvnVvDYC3It-fM',
    appId: '1:851082001759:android:84d13251749d5c63344aea',
    messagingSenderId: '851082001759',
    projectId: 'broetchen-29bf0',
    storageBucket: 'broetchen-29bf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfQn976-lu4GkQ_yDswIzyb3ROwlZaikA',
    appId: '1:851082001759:ios:1c3215caddfe3e1b344aea',
    messagingSenderId: '851082001759',
    projectId: 'broetchen-29bf0',
    storageBucket: 'broetchen-29bf0.appspot.com',
    iosClientId: '851082001759-408ejkm444l6ksrmo3v3ge5qthi2mjfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.broetchenshop',
  );
}
